review_user:
    resource: "@ReviewBundle/Controller/UserController.php"
    type:     annotation

review_teacher:
    resource: "@ReviewBundle/Controller/TeacherController.php"
    type:     annotation

review_student:
    resource: "@ReviewBundle/Controller/StudentController.php"
    type:     annotation

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

review:
    resource: "@ReviewBundle/Controller/"
    type:     annotation
    prefix:   /

logout:
    path : /logout